import Head from 'next/head'
import Tabs from "~/modules/home/components/Tabs";
import styled from "styled-components";
import {DummyFeedList} from "~/modules/home/utils";
import {Fragment} from "react";
import TravelPostCard from "~/components/TravelPostCard";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Parent>
                <div className='fixed-header'>
                <Tabs/>
                </div>
                <div className='scroll-container'>
                {DummyFeedList.map((item) => <Fragment key={item.id}>
                    <TravelPostCard {...item} />
                </Fragment>)}
                </div>
            </Parent>
        </>
    )
}
const Parent = styled.div`
  height: 100%;
  width: 100%;
  max-width: 850px;
  margin: 0 auto;
  position: relative;
  background: #f5f5f5;
  .scroll-container {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 80px 2rem 2rem 2rem;
    background: #f5f5f5;
  }
  .fixed-header {
    position: fixed;
    width: 100%;
    max-width: 850px;
    margin: 0 auto;
    top: 0;
  }
`;